#!/usr/bin/env fish

set -e

if [ (uname) = Linux ]
    sh (curl -L https://nixos.org/nix/install | psub) --no-daemon --no-channel-add --no-modify-profile
    exit
end

if [ $EUID = 0 ]
    echo "error: should not be run with sudo"
    exit 1
end

VERSION=2.24.2
SCRATCH=/tmp/nix-scratch

function cleanup
    cd /tmp
    rm -rf nix-$VERSION-aarch64-darwin nix-$VERSION-aarch64-darwin.tar.xz $SCRATCH
end
cleanup

mkdir $SCRATCH
cd /tmp
curl -O https://releases.nixos.org/nix/nix-$VERSION/nix-$VERSION-aarch64-darwin.tar.xz
tar -xf nix-$VERSION-aarch64-darwin.tar.xz
cd nix-$VERSION-aarch64-darwin

source create-darwin-volume.sh
sudo chown -R $USER /nix

sed -ie 's/INSTALL_MODE=daemon/INSTALL_MODE=no-daemon/g' install
./install --no-channel-add --no-modify-profile

cleanup
