'$schema' = 'https://jj-vcs.github.io/jj/latest/config-schema.json'

[colors]
'diff added token' = { underline = false }
'diff removed token' = { underline = false }

[ui]
diff-editor = ':builtin'

[ui.movement]
edit = true

[user]
name = 'tom'
email = 'tom@'
