[aliases]
d = ["diff"]
e = ["edit"]
l = ["log"]
n = ["next"]
p = ["prev"]
s = ["status"]

[colors]
"diff added token" = { underline = false }
"diff removed token" = { underline = false }

[ui]
default-command = "log"
diff-editor = ":builtin"

[ui.movement]
edit = true

[user]
name = "tom"
email = "tom@"

[template-aliases]
# TODO improve these
'friendly_name(c)' = '''
  coalesce(
      c.bookmarks().join(' '),
      '<' ++ c.change_id().shortest(4).prefix() ++ '>' ++ c.change_id().shortest(4).rest(),
  )
'''
prompt_refname = '''
  friendly_name(self) ++ if(empty, ' (' ++ parents.map(|p| friendly_name(p)).join(',' ) ++ ')')
'''
prompt_dirty = '!immutable && !empty'
