#!/usr/bin/env zsh

ln -sfv $0:A:h/zsh/zshenv ~/.zshenv

mkdir -p ~/.local/share/git
git config -f ~/.local/share/git/identity user.name $USER
git config -f ~/.local/share/git/identity user.email '\<\>'

touch ~/.hushlogin

if [[ $OSTYPE == darwin* ]]; then
  mkdir -p ~/.local/share/terminfo
  tic -xo $_/ $0:A:h/terminfo/backports.ti

  mkdir -p ~/Library/Application\ Support/iTerm2/DynamicProfiles
  ln -sfv $PWD/iterm2/profiles.json $_/

  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
fi

if ! [[ -d ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]]; then
  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
      ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi
zsh -c "if [[ -n \$commands[nvim] ]]; then
  export XDG_CONFIG_HOME=$0:A:h
  zsh -c 'nvim --headless -c \"autocmd User PackerComplete qa\" -c PackerSync'
fi"
