#!/usr/bin/env fish

cd (realpath (dirname (status -f))) || exit 1

function symlink
    if ! test -L $argv[2] || [ (realpath $argv[1]) != (realpath $argv[2]) ]
        if test -e $argv[2]
            echo -e "$(set_color red)\e[9m$argv[2]\e[0m$(set_color normal)"
            rm -rf $argv[2]
        end
        mkdir -p (dirname $argv[2])
        and ln -sfv (realpath $argv[1]) $argv[2]
    end
end

for d in fish fzf git helix ideavim jj readline rg shpool sqlite3
    symlink $d ~/.config/$d
end
symlink ssh/config ~/.ssh/config
symlink vim ~/.vim

touch ~/.hushlogin

mkdir -p ~/.local/state/{less,python,sqlite3,vim}

if [ (uname) = Darwin ]
    symlink iterm2/profiles.json ~/Library/Application\ Support/iTerm2/DynamicProfiles/profiles.json

    plutil -convert xml1 iterm2/settings.json -o - | defaults import com.googlecode.iterm2 -

    defaults write -g ApplePressAndHoldEnabled -bool false
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
end
