#!/usr/bin/env zsh

dir=$0:A:h

config_dirs=(
  git
  hg
  nvim
  tmux
  wezterm
)

dotfiles=(
  zsh/zshenv
)

create_dirs=(
  ~/.cache/zsh
  ~/.config
  ~/.local/share/{git,zsh}
  ~/.local/state/{less,zsh}
)

cleanups=(
  ~/.bash*(N)
  ~/.cache/{nvim,zsh}
  ~/.lesshst
  ~/.local/share/{git,nvim,terminfo,zsh}
  ~/.local/state/zsh/theme  # keep history
  ~/.local/state/{less,nvim}
  ~/.profile
  ~/.vim*(N)
  ~/.zcomp*(N)
  ~/.zlogin
  ~/.zlogout
  ~/.zprofile
  ~/.zsh*(N)
)

if [[ -f $dir/local/setup.zsh ]]; then
  source $dir/local/setup.zsh
fi

if [[ $1 == --clean-only ]]; then
  rm -rfv $cleanups ~/.config/${^config_dirs}*(N) ~/.${^dotfiles:t}(N)
  return
elif [[ $1 == --clean ]]; then
  rm -rfv $cleanups
fi

rm -rf ~/.config/${^config_dirs}*(N) ~/.${^dotfiles:t}(N)
mkdir -p $create_dirs
ln -sfv $dir/${^config_dirs} ~/.config
for f in $dotfiles; do
  ln -sfv $dir/$f ~/.$f:t
done

touch ~/.hushlogin

git_identity=~/.local/share/git/identity
mkdir -p $git_identity:h
git config -f $git_identity user.name $USER
git config -f $git_identity user.email '\<\>'

zsh -ilc 'nvim +qa 2> /dev/null'

if [[ $OSTYPE == darwin* ]]; then
  mkdir -p ~/.local/share/terminfo
  tic -xo $_/ $0:A:h/terminfo/backports.ti

  mkdir -p ~/Library/Application\ Support/iTerm2/DynamicProfiles
  ln -sfv $dir/iterm2/profiles.json $_

  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
fi
