theme = "tokyonight"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"
