theme = "match-fish"

[editor]
auto-pairs = false
color-modes = true
popup-border = "all"
rulers = [100]
text-width = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
right = [
  "diagnostics",
  "selections",
  "register",
  "file-encoding",
  "file-type",
  "spacer",
  "position-percentage",
  "spacer",
  "position",
]

[editor.whitespace.render]
default = "trailing"
tab = "all"

[keys.normal]
X = "select_line_above"
x = "select_line_below"

[keys.select]
X = "select_line_above"
x = "select_line_below"

[keys.normal.space]
"[" = ":set gutters.layout []"
"]" = ':set gutters.layout ["diagnostics","spacer","line-numbers","spacer","diff"]'
t = "file_browser"
T = "file_browser_in_current_buffer_directory"
w = ":toggle soft-wrap.enable"
W = '@<C-s>%<A-|>sudo tee "<C-r>%"<ret>:reload<ret><C-o>'
