[language-server]
ruff = { command = "ruff", args = ["server"] }
scls = { command = "simple-completion-language-server" }

[[language]]
name = "bash"
language-servers = ["bash-language-server", "scls"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server", "scls"]

[[language]]
name = "lua"
shebangs = ["lua", "luajit", "nvim"]
auto-format = true

[[language]]
name = "nix"
language-servers = ["scls"]
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "python"
language-servers = [
  { name = "ruff", except-features = [
    "hover",
  ] },
  "pylsp",
  "scls",
]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "txt"
scope = "source.txt"
file-types = ["txt"]
language-servers = ["scls"]

[[language]]
name = "toml"
language-servers = ["taplo", "scls"]
auto-format = true

[[language]]
name = "zsh"
grammar = "bash"
scope = "source.zsh"
injection-regex = "zsh"
file-types = [
  "zlogin",
  "zlogout",
  "zprofile",
  "zsh",
  "zshenv",
  "zshrc",
  { glob = "zsh/completion/*" },
  { glob = "zsh/functions/*" },
  { glob = "zsh/site-functions/*" },
  { glob = "zlogin" },
  { glob = "zlogout" },
  { glob = "zprofile" },
  { glob = "zshenv" },
  { glob = "zshrc" },
]
shebangs = ["zsh"]
comment-token = "#"
language-servers = ["scls"]
indent = { tab-width = 2, unit = "  " }
