[language-server.fish_lsp]
command = 'fish-lsp'
args = ['start']
environment.fish_lsp_show_client_popups = 'false'

[language-server.scls]
command = 'simple-completion-language-server'

[[language]]
name = 'bash'
language-servers = ['bash-language-server', 'scls']

[[language]]
name = 'css'
language-servers = ['vscode-css-language-server', 'scls']

[[language]]
name = 'fish'
language-servers = ['fish_lsp', 'scls']

[[language]]
name = 'git-config'
scope = 'source.gitconfig'
file-types = [
  { glob = '.gitmodules' },
  { glob = '.gitconfig' },
  { glob = '.git/config' },
  { glob = 'git/config' },
]
language-servers = ['scls']

[[language]]
name = 'html'
language-servers = ['vscode-html-language-server', 'scls']

[[language]]
name = 'ini'
language-servers = ['scls']

[[language]]
name = 'jjdescription'
language-servers = ['scls']

[[language]]
name = 'json'
language-servers = ['vscode-json-language-server']

[[language]]
name = 'markdown'
language-servers = ['vscode-markdown-language-server', 'scls']

[[language]]
name = 'sql'
language-servers = ['scls']

[[language]]
name = 'sshclientconfig'
file-types = [
  { glob = '.ssh/config' },
  { glob = 'ssh/config' },
  { glob = 'ssh_config' },
  { glob = 'ssh_config.d/*.conf' },
]
language-servers = ['scls']

[[language]]
name = 'toml'
language-servers = ['taplo', 'scls']
auto-format = true

[[language]]
name = 'txt'
scope = 'source.txt'
file-types = ['txt']
language-servers = ['scls']

[[language]]
name = 'typescript'
language-servers = ['typescript-language-server', 'scls']

[[language]]
name = 'xml'
language-servers = ['scls']

[[language]]
name = 'yaml'
language-servers = ['yaml-language-server', 'scls']
auto-format = true
