if has("ide")
  source ~/.vim/helix-vim/helix.idea.vim
else
  unlet! skip_defaults_vim
  source $VIMRUNTIME/defaults.vim
  source ~/.vim/helix-vim/helix.vim
endif

set autoread
set background=dark
set clipboard=unnamed,unnamedplus
set colorcolumn=80
set expandtab
set foldlevel=99
set foldmethod=syntax
set hidden
set hlsearch
set ignorecase
set linebreak
set nojoinspaces
set noswapfile
set number
set scrolloff=2
set shiftwidth=2
set smartcase
set smartindent
set softtabstop=2
set viminfofile=~/.local/state/vim/viminfo

if has("ide")
  set clipboard+=ideaput
  set ideajoin
  set idearefactormode=keep
else
  colorscheme slate
  silent! colorscheme habamax

  let &t_SI = "\e[5 q"
  let &t_EI = "\e[2 q"
endif

nnoremap <Space><Space>[ <Esc>:set nonumber<CR>
nnoremap <Space><Space>] <Esc>:set number<CR>
nnoremap <Space><Space>w <Esc>:set invwrap<CR>
nnoremap <Space><Space>W <Esc>:w !sudo tee > /dev/null %<CR>
