#!/usr/bin/env zsh

if [[ -z $commands[brew] ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval $(/opt/homebrew/bin/brew shellenv)
fi

brew bundle install --no-lock --file=$0:h/Brewfile
brew cleanup -s
