#!/usr/bin/env fish

if [ "$argv[1]" = --open-tree ]
    exec tmux display-popup -Eh 85% -w 85% hxt --tree $argv[2]
else if [ "$argv[1]" = --tree ]
    set files (yazi --chooser-file=/dev/stdout "$argv[2]")
    if [ -n "$files" ]
        tmux send ":open $files" Enter
    end
else
    TMUX= exec tmux -f (echo \
        'set -s exit-unattached on
         set -s focus-events on
         set -g prefix C-y
         set -g status off
         bind -n C-z suspend-client' | psub) new -s (tty) hx $argv >/dev/null
end
