tap 'fish-shell/fish-beta-4'
tap 'homebrew/bundle'
tap 'tom/homebrew', 'https://git.koholi.net/tom/homebrew.git'

brew 'bash-language-server'
brew 'fd'
brew 'fish-shell/fish-beta-4/fish'
brew 'fish-lsp'
brew 'fzf'
brew 'helix'
brew 'jj'
brew 'ncdu'
brew 'pstree'
brew 'python-lsp-server'
brew 'tom/homebrew/simple-completion-language-server'
brew 'sqlite', link: true
brew 'taplo'
brew 'typescript-language-server'
brew 'vscode-langservers-extracted'
brew 'yaml-language-server'

if OS.linux?
  brew 'tom/homebrew/shpool'
end

if OS.mac?
  tap 'artginzburg/tap'
  tap 'homebrew/services'

  brew 'coreutils'
  brew 'diffutils'
  brew 'dos2unix'
  brew 'file', link: true
  brew 'findutils'
  brew 'gnu-sed'
  brew 'gnu-tar'
  brew 'grep'
  brew 'gzip'
  brew 'htop'
  brew 'man-db'
  brew 'moreutils'
  brew 'mtr'
  brew 'p7zip'
  brew 'progress'
  brew 'pv'
  brew 'ripgrep'
  brew 'shellcheck'
  brew 'tree'
  brew 'unar'
  brew 'util-linux', link: true
  brew 'watch'
  brew 'wget'

  brew 'cliclick'
  brew 'exiftool'
  brew 'ffmpeg'
  brew 'imagemagick'
  brew 'mas'
  brew 'mediainfo'
  brew 'oxipng'
  brew 'rclone'
  brew 'sudo-touchid'

  cask 'aegisub'
  cask 'android-platform-tools'
  cask 'audacity'
  cask 'firefox'
  cask 'ghostty'
  cask 'gog-galaxy'
  cask 'gramps'
  cask 'handbrake'
  cask 'iina'
  cask 'istat-menus@6'
  cask 'jdownloader'
  cask 'krita'
  cask 'makemkv'
  cask 'mkvtoolnix'
  cask 'musicbrainz-picard'
  cask 'scummvm'
  cask 'steam'
  cask 'stolendata-mpv'
  cask 'the-unarchiver'
  cask 'whisky'
  cask 'windows-app'

  mas 'Bitwarden', id: 1352778147
  mas 'Numbers', id: 409203825
  mas 'Pages', id: 409201541
end
