set -g aggressive-resize on
set -s escape-time 0
set -s focus-events on
set -g history-limit 10000
set -g mouse on
set -s set-clipboard on

set -g message-command-style "bg=color0"
set -g message-style "bg=color0"
set -g mode-style "bg=color0"
set -g pane-active-border-style "fg=color8"
set -g pane-border-style "fg=color0"
set -g status-style "fg=color8 bg=color0"

bind ] paste-buffer -p
bind c new-window -c "#{pane_current_path}"
bind l {
  send C-l
  run "sleep .1"
  clear-history
}

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -n WheelUpPane {
  select-pane -t=
  if -F "#{alternate_on}" {
    if -F "#{mouse_any_flag}" {
      send -M
    } {
      send -N5 up
    }
  } {
    if -F "#{pane_in_mode}" {
      send -M
    } {
      copy-mode -e
    }
  }
}

bind -n WheelDownPane {
  select-pane -t=
  if -F "#{?mouse_any_flag,,#{alternate_on}}" {
    send -N5 down
  } {
    send -M
  }
}

bind -T copy-mode-vi ? command-prompt -ip ? {
  send -X search-backward-incremental "%%%"
}
bind -T copy-mode-vi / command-prompt -ip / {
  send -X search-forward-incremental "%%%"
}
bind -T copy-mode-vi y send -X copy-pipe
