set -g aggressive-resize on
set -g allow-passthrough on
set -s default-terminal 'tmux-256color'
set -g display-time 1500
set -s escape-time 0
set -s focus-events on
set -g history-limit 100000
set -g mouse on
set -s set-clipboard on
set -g status-interval 5
set -s terminal-overrides[10] 'linux*:sitm=:ritm='
set -g update-environment[10] 'FONT_MODE'

run '#{d:current_file}/../zsh/functions/theme apply --tmux'

set -g prefix C-a
bind C-a send-prefix
unbind C-b

bind -n WheelUpPane {
  select-pane -t=
  if -F '#{alternate_on}' {
    if -F '#{mouse_any_flag}' {
      send -M
    } {
      send -N5 up
    }
  } {
    if -F '#{pane_in_mode}' {
      send -M
    } {
      copy-mode -e
    }
  }
}

bind -n WheelDownPane {
  select-pane -t=
  if -F '#{?mouse_any_flag,,#{alternate_on}}' {
    send -N5 down
  } {
    send -M
  }
}

bind c new-window -c '#{pane_current_path}'

bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind -n M-k {
  if -F '#{==:#{pane_current_command},nvim}' {
    send M-k
  } {
    run -C '#{@force-select-pane-u}'
  }
}
bind -n M-j {
  if -F '#{==:#{pane_current_command},nvim}' {
    send M-j
  } {
    run -C '#{@force-select-pane-d}'
  }
}
bind -n M-h {
  if -F '#{==:#{pane_current_command},nvim}' {
    send M-h
  } {
    run -C '#{@force-select-pane-l}'
  }
}
bind -n M-l {
  if -F '#{==:#{pane_current_command},nvim}' {
    send M-l
  } {
    run -C '#{@force-select-pane-r}'
  }
}
set -g @force-select-pane-u {
  select-pane -U
  if -F '#{==:#{pane_current_command},nvim}' {
    send-keys M-J
  }
}
set -g @force-select-pane-d {
  select-pane -D
  if -F '#{==:#{pane_current_command},nvim}' {
    send-keys M-K
  }
}
set -g @force-select-pane-l {
  select-pane -L
  if -F '#{==:#{pane_current_command},nvim}' {
    send-keys M-L
  }
}
set -g @force-select-pane-r {
  select-pane -R
  if -F '#{==:#{pane_current_command},nvim}' {
    send-keys M-H
  }
}

bind -T copy-mode-vi ? command-prompt -ip ? \
    'send -X search-backward-incremental "%%%"'
bind -T copy-mode-vi / command-prompt -ip / \
    'send -X search-forward-incremental "%%%"'
bind -T copy-mode-vi y send -X copy-pipe
run -C 'bind R source "#{current_file}" \; display "Reloaded tmux.conf"'

source -qF '#{d:current_file}/../local/tmux/tmux.conf'
