autoload -U add-zle-hook-widget
autoload -U add-zsh-hook
autoload -U run-help && unalias -m run-help
autoload -U zargs
autoload -U zmv
zmodload zsh/datetime
zmodload zsh/mapfile
zmodload zsh/terminfo
zmodload zsh/zle

setopt extendedglob
setopt globstarshort
setopt interactivecomments

path=({$ZDOTDIR_LOCAL:h,$ZDOTDIR:h}/bin(N) $path)
fpath=({$ZDOTDIR_LOCAL,$ZDOTDIR}/{completion,functions}(N) $fpath)

source $ZDOTDIR/includes/termdetect.zsh

source $ZDOTDIR/includes/commands.zsh
source $ZDOTDIR/includes/cursor.zsh
source $ZDOTDIR/includes/history.zsh
source $ZDOTDIR/includes/keys.zsh
source $ZDOTDIR/includes/nav.zsh
source $ZDOTDIR/includes/theme.zsh
source $ZDOTDIR/includes/title-cwd.zsh

source $ZDOTDIR/includes/completion.zsh
source $ZDOTDIR/includes/syntax-highlighting.zsh

if [[ -f $ZDOTDIR_LOCAL/zshrc ]]; then
  source $ZDOTDIR_LOCAL/zshrc
fi
